#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  1 18:58:19 2018

@author: chenchuqiao
"""
#for debug and examine
#enricheddic['financial_disclosure']
#enricheddic['jobs']
#enricheddic['crm']
#enricheddic['marketing_and_sales']



enricheddic = {'financial_disclosure': 
    {'margin', 'joined', 'centrals', 'led', 'acquires', 'joining', 'opennesses', '$', 'located', 'strategies', 'investitures', 'promote', 'appointed', 'acquisitivenesses', 'center', '3q', 'board of director', 'second-quarter', '2nd-quarter', 'locations', 'junction', 'junctions', 'Earnings call', 'opens', 'closured', 'branch', 'acquisition', 'open', 'closer', 'closing', 'per share', 'marginal', 'lead', 'location', 'investor', 'first-quarter', 'third-quarter', 'opener', 'strategists', '3rd-quarter', 'investors', 'invests', 'Expanding', 'invest', 'acquirings', 'leadership', '4th-quarter', 'investings', 'promoters', 'promoted', 'fourth-quarter', 'Opening', 'law makers', 'diluted', 'openness', 'branching', 'Q1', 'S&P', 'Investor', 'Earnings', 'Closing', 'leaders', 'acquirer', 'join', '2q', 'opening', 'Q2', 'strategical', 'joiners', 'locaters', 'Q4', 'promotion', 'CFOES', 'openers', 'locating', 'closure', 'strategic', '1st-quarter', 'new branch', 'closuring', 'closes', 'strategically', 'acquired', 'junctures', 'leading', 'promotive', 'investment', 'acquire', 'Announce Partnership', 'promoter', 'branches', 'acquirers', 'closely', 'strategist', 'close', 'central', 'marginally', 'locate', 'centering', 'centrical', 'closeness', 'EPS', 'investiture', 'locater', 'promotions', 'centralities', 'leaderships', 'press release', 'acquirable', 'new office', 'revenues', 'cent', 'acquisitiveness', 'CFO', 'closed', 'centrally', 'Opening soon', 'marginalities', 'openings', 'centers', 'joins', 'investments', 'acquisitions', 'promoting', 'closures', 'joiner', 'openly', 'opened', 'leads', 'branchy', 'leader', 'closings', 'centrality', 'locates', 'promotes', 'marginality', 'margins', 'locators', 'investing', 'jointure', 'strategy', 'closers', 'revenue', '1q', '4q', 'acquisitive', 'jointures', 'joinings', 'locator', 'branched', 'closenesses', 'invested', 'Conference call', 'juncture', 'acquiring', 'centric', 'cents', 'Q3', 'Investor Conference', 'centerings'}, 
    'crm': 
    {'congrats', 'too', 'cooled', 'coolness', 'conferences', 'prettinesses', 'sorry', 'helped', 'funnies', 'conferring', 'expoes', 'agreeableness', 'pleasant', 'coolings', 'helper', 'cools', "that's great", 'coolly', 'create', 'great', 'recommendation', 'waiter', 'agreement', 'joining us', 'waiters', 'prettily', 'hey there', 'did you know', 'DM', 'haha', 'sure', 'pleasures', 'his', 'lookers', 'helpers', 'wowing', 'coolnesses', 'apologize', 'soundnesses', 'welcoming', 'creates', 'please', 'hi', 'hopers', 'geniuses', 'gladness', 'creatures', 'soundness', 'solidnesses', 'gladnesses', 'anniversaries', 'solidifications', 'thank you', 'waits', 'cooler', 'agreeable', 'pleases', 'funninesses', 'solids', 'conferees', 'funs', 'creator', 'agrees', 'thank', 'hoper', 'solid', 'account information', 'excelent', 'solidly', 'greatly', 'solidifies', 'wow', 'conference', 'for sure', 'welcomers', 'sounded', 'recommending', 'solidities', 'soundings', 'solidity', 'classic', 'thanks', 'excited for', 'glads', 'greatness', 'creature', 'helpings', 'confers', 'Creations', 'pleasings', 'contact', 'creativities', 'created', 'coolers', 'greats', 'creatively', 'waiting', 'surenesses', 'creating', 'recommend', 'wows', 'conferrals', 'sounds', 'looks', 'glad', 'pleasure', 'shoutout', 'welcome', 'looking', 'pleasantnesses', 'helps', 'pleasing', 'agreeably', 'soundly', 'Creation', 'pleasingly', 'birthday', 'apologized', 'prettiness', 'funny', 'recommends', 'creative', 'yay', 'inspired', 'idnetity theft', 'sounder', 'oh', 'apologies', 'birthdays', 'thanked', 'creativenesses', 'apology', 'gladly', 'waitings', 'sounding', 'coolants', '@', 'automated call', 'expo', 'looker', 'cooling', 'congradulations', 'recommended', 'conferments', 'conferee', 'welcomer', 'agreeability', 'genius', 'awesome', 'solidifying', 'pleased', 'fun', 'wowed', 'pleasantness', 'beautifully', 'pleasances', 'conferral', 'waited', 'agreeing', 'anniversary', 'pleasantly', 'contacting', 'hopes', 'apologist', 'creations', 'apologizing', 'hoping', 'creation', 'apologise', 'solidifyings', 'agree', 'creativity', 'apologizes', 'agreeabilities', 'sonants', 'creativeness', 'DMS', 'hello', 'ah', 'agreed', 'apologetically', 'hoped', 'classics', 'agreeablenesses', 'looked', 'pretty', 'agreements', 'surely', 'wait', 'thanking', 'helping', 'pleaser', "You're welcome!", 'sureness', 'sound', 'greatnesses', 'funniness', 'how to', 'help', 'sonant', 'coolant', 'solidness', 'funnily', 'confer', 'conferred', 
     'welcomes', 'hope', 'fraudulant', 'contacts', 'helloes', 'conferment', 'sorrinesses', 'cool', 'apologetic', 'solidify', 'apologists', 'welcomed', 'solidification', 'beautiful', 'pleasers', 'sounders', 'contacted', 'You', 'solidified', 'recommendations', 'creators', 'look', 'pleasance', 'sorriness', 'please call'}, 'marketing_and_sales': {'launcher', 'eventuated', 'registries', 'shop', 'enjoying', 'black friday', 'eventuating', 'registering', 'happy holidays', 'funnies', 'experiencing', 'daily', 'watches', 'dealingss', 'deals', 'registered', 'tune in', 'promote', 'celebrating', 'president day', 'seminars', 'symposiums', 'happiness', 'easterlies', 'sneak peek', 'enjoyed', 'see our', 'events', 'watchers', 'watched', 'shopping', 'celebrations', 'eventuates', 'discount', 'discounters', 'new year', 'celebrator', 'enjoyment', 'innovate', 'deal', 'holidays', 'holiday weekend', 'discussant', 'experienced', 'innovator', 'discussing', 'dealing', 'celebrate', 'Now available', 'celebratory', 'check us out', 'FDAS', 'discounter', 'CEO', 'funninesses', 'launching', 'funs', 'celebrated', 'registrants', 'enjoyments', 'find tips', 'promoters', 'enjoy', 'innovativeness', 'promoted', 'shops', 'easters', 'conferenceCheck out new', 'contact', 'Shoutout', 'experience', 'happinesses', 'registers', 'stop by', 'watcher', 'discounted', 'workshops', 'celebrates', 'dealer', 'holidayed', 'find out', 'innovated', 'manufacturings', 'launched', 'congrat', 'promotion', 'registrations', 'scholar', 'symposium', 'innovativenesses', 'CFOES', 'innovation', 'launches', 'scholarly', 'watchings', 'easts', 'hosting', 'enjoys', 'join us', 'celebration', 'promotive', 'enjoyers', 'Learn more', 'Press', 'funny', 'registrant', 'innovators', 'promoter', 'discounting', 'discussions', 'dailies', 'introducing', 'discounts', 'innovates', 'get started', 'launch', 'enjoyer', 'innovational', 'celebrants', 'check it out', 'discussed', 'dealerships', 'dealers', 'celebrant', 'congradulations', 'shopper', 'earth day', 'registration', 'fun', 'innovations', 'contacting', 'promotions', 'would you like', 'shopped', 'discussants', 'watch', 'register', 'watching', 'innovating', 'Extending', 'news', 'happy', 'dealership', 'scholarship', 'independence day', 'discusses', 'CFO', 'east', 'innovative', 'manufacturing', 'mark you calendar', 'workshop', 'launchers', 'promoting', 'scholars', 'get your new', 'shoppings', 'memorial day', 'celebrators', 'experiential', 'experiences', 'dealt', 
                                                                                                                                                                                                                                                                                                                              'event', 'funniness', 'registry', 'promotes', 'discussion', 'happily', 'dealings', 'days', 'Donate', 'holidaying', 'CEOS', 'easter', 'funnily', 'easterly', 'holiday', 'webinar', 'newsy', 'Donation', 'contacts', 'Join Event', 'promo code', 'seminar', 'eventuate', '#', 'millenials', 'contacted', 'discuss', 'FDA', 'Live', 'scholarships', 'only at', 'shoppers', 'experient', 'day'}, 
    'jobs': 
    {'recruits', 'recruited', 'recruitments', 'recruiting', 'apply online', 'linkedin', 'hiring', 'recruiters', 'recruitment', 'recruit', 'Job Openings', 'recruiter', 'Join Job'}}